import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="flex gap-4 p-3 text-2xl justify-center border-2 border-gray-500">
          <Link href="/">Home</Link>
          <Link href="/dashboard/settings">Setting</Link>
          <Link href="/dashboard/analyatics">Analyatics</Link>
          <Link href="#">About</Link>
          <Link href="#">Go</Link>
        </section>
        <section>{children}</section>
      </body>
    </html>
  );
}
